config/routes.rb
Portfolio::Application.routes.draw do
  devise_for :users

  root to: 'portfolio#home'
  
  get "portfolio/home"
  
  namespace :blog do
    resources :users
    resources :dashboard
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
   
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/blog/blog_controller.rb
class Blog::BlogController < ApplicationController
  
  layout 'blog'
end

app/controllers/blog/dashboard_controller.rb
class Blog::DashboardController < Blog::BlogController
  
  def index
    
  end
    
end

app/controllers/blog/users_controller.rb
class Blog::UsersController < Blog::BlogController

  def index
    
  end
  
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def home    
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog/blog_helper.rb
module Blog::BlogHelper
end

app/helpers/blog/dashboard_helper.rb
module Blog::DashboardHelper
end

app/helpers/blog/users_helper.rb
module Blog::UsersHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
  def gravatar_for
    gravatar_id = Digest::MD5::hexdigest("vajapravin23@gmail.com".downcase)
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png"
    image_tag(gravatar_url, alt: 'vajapravin', class: "photo")
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<nav>
				<ul class="nav pull-right">
					<li>
						<%= link_to "Dashboard", '#' %>
					</li>
					<li>
						<%= link_to "Users", '#' %>
					</li>
					<% if signed_in? %>					
					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b> </a>
						<ul class="dropdown-menu">
							<li>
								<%= link_to "Profile", '#' %>
							</li>
							<li>
								<%= link_to "Settings", '#' %>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
							</li>
						</ul>
					</li>
					<% else %>
					<li>
						<%= link_to "Sign in", new_user_session_path %>
					</li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_header.html.erb
<header>
	<!-- HTML5 header tag -->
	<div id="headercontainer">
		<h1><a class="introlink anchorLink" href="#intro">Mobile Application Developer</a></h1>
		<div class="menu-top">
			<nav>
				<!-- HTML5 navigation tag -->
				<ul>
					<li>
						<a class="introlink anchorLink" href="#intro">Intro</a>
					</li>
					<li>
						<a class="portfoliolink anchorLink" href="#portfolio">Portfolio</a>
					</li>
					<li>
						<%= link_to 'Blogs', blog_dashboard_index_path, :class => "contactlink" %>
					</li>

					<li>
						<a class="aboutlink anchorLink" href="#about">About</a>
					</li>
					<li>
						<a class="contactlink anchorLink" href="#contact">Contact</a>
					</li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Portfolio</title>

		<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700|Expletus+Sans|Lovers+Quarrel' rel='stylesheet' type='text/css'>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js" type="text/javascript"></script>
		<script src="js/jquery.anchor.js" type="text/javascript"></script>
    	<script src="js/jquery-fancybox.js" type="text/javascript"></script>
    	<%= stylesheet_link_tag    "application", media: "all" %>
	    <%= javascript_include_tag "application" %>
	    <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Portfolio</title>

		<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700|Expletus+Sans|Lovers+Quarrel' rel='stylesheet' type='text/css'>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js" type="text/javascript"></script>
		<script src="js/jquery.anchor.js" type="text/javascript"></script>
    	<script src="js/jquery-fancybox.js" type="text/javascript"></script>
    	<%= stylesheet_link_tag    "application", media: "all" %>
	    <%= javascript_include_tag "application" %>
	    <%= csrf_meta_tags %>
	</head>
	<body>		
		<%= render './blog/header' %>
		<div class="container">			
			<%= yield %>
		</div>
	</body>
</html>

app/views/portfolio/home.html.erb
<section id="intro">
	<div class="center-intro hero-unit">
		<headline>
			Vajapravin
			<p><span>Mobile Application Developer</span></p>
		</headline>
		<div align="left" class="article">
			<h1>Pravin Vaja</h1>
			<hr>			
			<%= gravatar_for %>
			<!-- <img class="photo" src="/img/jonas-jared-jacek.jpg" alt="Jonas Jacek" height="150" width="120" /> -->
			<pre>I am a Mobile Application Developer {Android & Blackberry} working at Define Labs which provide software design and development services for Mobile and the Web in Pune which I founded in 2011. The focus of my work — in general — is on Android, Blackberry Development as per client requirement.</pre>			
		</div>
	</div>
</section>

<section id="portfolio">
	<div class="center-portfolio hero-unit">
		<div align="left" class="portfolio">
			<h1>My Portfolio :)</h1>
			<hr>
			<pre>I have experience on Android and Blackberry Mobile Application Development which is based on Web Services, C2DM, Google Map, Theme, Social Network, also Facebook, LinkedIn and Twitter for profile and various APIs.</pre>		
		</div>	
	</div>
</section>

<section id="about">
	<div class="center-portfolio hero-unit">
		<div align="left" class="about">
			<h1>About Me!</h1>
			<hr>
			<pre>I have experience on Android and Blackberry Mobile Application Development which is based on Web Services, C2DM, Google Map, Theme, Social Network, also Facebook, LinkedIn and Twitter for profile and various APIs.</pre>		
		</div>	
	</div>
</section>


<section id="contact">
	<div class="center-portfolio hero-unit">
		<div align="center" class="contact">
			<h1>@ Contact Me</h1>			
			<hr>
			<h1>						
			<table border=0 cellpadding="20">
				<tr>
					<td>Email:</td><td>vajapravin23@gmail.com</td><td align="center">
						<a href='http://www.facebook.com/vajapravin'>facebook</a></td>				</tr>
				<tr>
					<td>Phone:</td><td> +91-9766847415 </td><td align="center">
						<a href='http://stackoverflow.com/users/959712/vajapravin'>stackoverflow</a></td>				</tr>					
				</tr>
			</table>
			</h1>
		</div>	
	</div>
</section>